### ISSUE TITLE
Pasting support for the editor

### ISSUE THREAD

**Issue by arisolt** [nadrad/h-m-m#10]
Not sure if this is isolated to my machine. I am unable to Paste from the clipboard when editing a node. Is this normal?

I'm on Mojave 10.14.6 for what it's worth.

**Comment by nadrad** [comment]
Can you send me the output of the following command?

`php -r 'echo PHP_OS_FAMILY;'`

**Comment by arisolt** [comment]
That would be Darwin

**Comment by arisolt** [comment]
`pbpaste` work correctly in the terminal. 
copying from h-m-m into another application also works correctly. 
copying text from another application, then using command `P` in h-m-m correctly pastes the content as a new node. 
only when activating edit mode for a node using command `e`, it won't insert the clipboard text when pasting it (either using cmd+v, or right-click -> paste)

**Comment by nadrad** [comment]
Oh, I see... I never included that in the editing feature :) 
I'll add it in the future.

**Comment by nadrad** [comment]
I've renamed the title to be clearer to me later on.

**Comment by arisolt** [comment]
that would be a very useful feature imo :)

**Comment by nadrad** [comment]
Done (ctrl+v)

**Comment by arisolt** [comment]
something funky is going on. copy-pasting the below text (or any other text) results in this behaviour. 

> Many users simply launch a new shell or open a new terminal window, but there is no need to do that, there’s a way to directly refresh the profile in use thanks to the source command. 

![image](https://user-images.githubusercontent.com/2144830/190597801-9ec6bdc1-d8b9-4968-9b71-aaa00a3c6018.png)

**Comment by nadrad** [comment]
Can you make sure you're using the latest version? The last few commits solved a few issued related to multi-byte characters in the editor. 

If you still had the problem, please save the file and upload it here because when you paste the text as you've done before, github may clean up some of the control characters (that may be why I don't see a problem when I paste it in my machine).

**Comment by arisolt** [comment]
just cloned the repo again. for what it's worth, i get the issue also when i copy from the github post. 
[test.txt](https://github.com/nadrad/h-m-m/files/9582796/test.txt)

**Comment by nadrad** [comment]
There are a few "delete" characters inside your file, and that's causing the problem. The fact that you have problems when copying text from the comment above when I don't is that either my system is automatically removing the control characters or your system is adding them for some reason. 

Regardless, I've added something to remove all control characters from the text read from the file, clipboard, and direct entry. I think it should be fine for you now... let me know.

**Comment by jonas-w** [comment]
The normal way of pasting in my terminal (alacritty on archlinux), or in most of the other terminals, is to press Ctrl+Shift+V and when i paste the normal way it also makes some funny stuff.

But your keybinding with Ctrl+V works perfectly.

**Comment by nadrad** [comment]
It's funny... when the user presses ctrl+shift+v, the application doesn't receive the ctrl+shift+v sequence, but receives the actual content! Because I didn't expect to receive such a long input, it was split in multiple loops, and because each loop expected one character, the cursor wasn't moving enough and the next round... you get it. 

Anyway, it's covered now, and ctrl+shift+v should work fine in the editor.

**Comment by jonas-w** [comment]
Seems to work fine, thanks! (At least on linux, idk about Mac)

**Comment by arisolt** [comment]
confirmed pasting now works on mac too. good stuff :)

**Comment by nadrad** [comment]
Finally! Dealing with those control characters was a little tricky. We forget about those things when working with high-level programs.
