### ISSUE TITLE
Undesired characters before "Saved..." message after saving with the "s" keybinding

### ISSUE THREAD

**Issue by llagerlof** [nadrad/h-m-m#36]
Fedora 36 / gnome-terminal / Bash

---

When I save using "s", a strange output appear before "Saved..." message.

![hmm-characters-strange](https://user-images.githubusercontent.com/193798/191777028-c2b313ab-274c-4e48-bbdc-04bf191c4a1b.png)

**Comment by nadrad** [comment]
That could only happen if the terminal width is zero in one of the formulas. However, if the application can't detect the terminal width correctly, lots of things must go wrong.

I've made some changes, and it probably works fine for you now. However, please check to see whether the message is aligned to the left or right of the screen and let me know, so that I can understand the underlying cause.

**Comment by llagerlof** [comment]
Thank you. The strange output vanished.

Now the message is aligned to the right of the screen.
