### ISSUE TITLE
Connecting nodes

### ISSUE THREAD

**Issue by raf2000** [nadrad/h-m-m#45]
Sometimes things are related(ish). A feature that would allow to connect nodes from different trees/parents (maybe with dots or dashes) could be helpful. What do you think?

**Comment by nadrad** [comment]
I think that makes the code too complicated without providing enough benefits.

Sometimes I run into cases when an extra relationship seems necessary, but I can solve it by changing the structure of my tree. Sometimes the new structure gives a clearer view of what's going on, which helps my thought process.

That being said, the one-to-many relationships in a tree may not be suitable for some types of content, and you may need many-to-many relationships in a general graph. In that case, it's a good idea to use an application designed for working with graphs instead. I can't recommend anything because I've never needed one, but there must be many of them.
