### ISSUE TITLE
Feature Request: change order of '✓' and '✗'

### ISSUE THREAD

**Issue by agschaid** [nadrad/h-m-m#47]
Hi,

I am using '✓' and '✗' (toggled by `t`) extensively to mark TODOs in my mindmaps, where ''✗' marks an open TODO and '✓' a done one.

Now given this is how it was intended to be used, I think the toggle order is wrong.

Currently it is '' -> '✓' -> '✗'
So if want to turn a node into a TODO I have to hit `t` **twice**.
If I want to mark a TODO as done I have to hit `t` **twice again**.

Not horrible. But not good.

Maybe you had a different usecase in mind but I for one would like to suggest to change to toggle order to '' -> '✗' -> '✓' which would streamline the workflow described above.

Thank you very much, by the way. If been using h-m-m for two weeks now and I am starting to wonder how I was able to live without it.

**Comment by nadrad** [comment]
I'm glad you like it :)

Yes, the use case was different: I normally use it for accepting or rejecting ideas/requirements/elements. 

However, when we make the final decision about the building elements of each branch, I sometimes use it to track what is done, probably similar to what you do. For that, the "to do" items are left without a mark, those that are completed get a check mark, and those we decide to exclude during execution get a cross. I usually press `T` after each update as well to sort them based on their state: to do items come first, followed by completed, and then excluded items.

Would that be a good process for you as well? I guess that's mainly useful if you change your mind during execution, otherwise the cross mark remains unused. 

Something that might be useful to many use cases (including your original one) is a key binding to add either of the marks to all siblings of the selected item. The only problem is that I'm running out of available keys for new key bindings!

**Comment by agschaid** [comment]
ok. I get it.

concerning the additional key binding: thank you! But don't do it for me ;). I am good.
besides it does not really meet my needs: adding a mark to all children would make sense if I had one "ToDos" node per mindmap. But I moved away from that pretty quickly and now leave ToDo-Marks scattered across my mindmap (always where the most/best context is provided)
So that's why I explicitly "need" to mark my ToDos as such.

As I said: I am good (well there ARE some other feature requests in my mind. But that's for another day.)

Please feel free to close the issue.

**Comment by nadrad** [comment]
So, I thought a lot about it, and I came up with a solution that can be general enough and useful to many users: Now, you can customize the two symbols using `symbol1` and `symbol2`.

So, for your case, instead of leaving it to the default (✓,✗), you can define it as (✗,✓) in your config.

By the way, in case you're wondering, changing this setting wouldn't change anything in your existing files, and they remain as they were. It only changes what happens when you press the `t` key afterward.

**Comment by agschaid** [comment]
oh!
that's actually a very cool solution ;)

thank you

**Comment by nadrad** [comment]
Yes, indeed a good idea. Something for the future :)

**Comment by agschaid** [comment]
tried it.
works like a charm.
thank you.
