### ISSUE TITLE
Ability to add color for each node and sub nodes

### ISSUE THREAD

**Issue by samuellawerentz** [nadrad/h-m-m#56]
I'm not sure, if this is too much to ask. It would be awesome if we have the ability to select a color for a node.

## Workflow:
On any active node, press a key (For Eg `c`) which would cycle through the colors listed in the config file.

#### Additional features:
- We can have a separate key `C` to color all the sub nodes
- Toggle color view (Turn on/off the colors)

**Comment by nadrad** [comment]
I think having the option to highlight nodes can be useful. It needs some effort to implement it, though... but it's probably worth it. 

I'll add it soon.

**Comment by nadrad** [comment]
I spent some time on it, and it turned out to be way more complicated than I expected! 

I'm going to rewrite h-m-m it in a different language in the future, and for that rewrite, I'll use a more general approach to showing the map which can allow easy highlighting. So, I'm going to close it for the current implementation.

By the way, for now, consider changing the symbol to something more eye-catching and use that as a substitute for highlighting.
