### ISSUE TITLE
Ubuntu 24.04 with Xclip Docker cannot yank. 

### ISSUE THREAD

**Issue by pbower** [nadrad/h-m-m#82]
Hi there,

I followed the docker installation, and have xclip installed with PHP 8.

PHP 8.3.6 (cli) (built: Jun 13 2024 15:23:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.6, Copyright (c), by Zend Technologies
    
    xclip version 0.13
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL

When yanking, it says :

Error: Can't open display: (null)

When pasting, it says :

Error: Can't open display: (null)
Deprecated: mb_ereg_replace(): Passing null to parameter #3 ($string) of type string is deprecated in /app/h-m-m on line 2979

Is there a reason for this, or is it a bug ?

Thanks,
Pete

**Comment by nadrad** [comment]
Some resources say that this error can be because of running xclip over ssh, and that it can be solved by changing some settings; e.g., this article: https://www.cyberciti.biz/faq/linux-unix-macos-fix-error-cant-open-display-null-with-ssh-xclip-command-in-headless/

Please make sure the suggested settings are safe before applying them.
